apiVersion: v2
type: application
name: mdai-cluster
version: 0.0.5
description: MDAI Cluster helm chart
appVersion: 0.0.5
dependencies:
  - name: opentelemetry-operator
    version: 0.71.2
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-operator.enabled
  - name: kube-prometheus-stack
    version: 65.3.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-prometheus-stack.enabled
  - name: metrics-server
    version: 3.12.1
    repository: https://kubernetes-sigs.github.io/metrics-server
    condition: metrics-server.enabled
  - name: mdai-api
    version: 0.0.5
    repository: file:///Users/robin/code/mdai-api/deployment
    condition: mdai-api.enabled
  - name: mdai-console
    version: 0.2.4
    repository: https://decisiveai.github.io/mdai-helm-charts
    condition: mdai-console.enabled
  - name: datalyzer
    version: 0.0.6
    repository: https://decisiveai.github.io/mdai-helm-charts
    condition: datalyzer.enabled
  - name: mydecisive-engine-operator
    alias: mdai-operator
    version: 0.0.14
    repository: https://decisiveai.github.io/mdai-helm-charts
    condition: mdai-operator.enabled
