apiVersion: v2
type: application
name: mdai-cluster
version: 0.0.2
description: MDAI Cluster helm chart
appVersion: 0.0.2
dependencies:
  - name: opentelemetry-operator
    version: 0.43.1
    repository: https://decisiveai.github.io/mdai-helm-charts
    condition: opentelemetry-operator.enabled
  - name: prometheus
    version: 25.24.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: metrics-server
    version: 3.12.1
    repository: https://kubernetes-sigs.github.io/metrics-server
    condition: metrics-server.enabled
  - name: mdai-api
    version: 0.0.4
    repository: https://decisiveai.github.io/mdai-helm-charts
    condition: mdai-api.enabled
  - name: datalyzer
    version: 0.0.6
    repository: https://decisiveai.github.io/mdai-helm-charts
    condition: datalyzer.enabled
  - name: mydecisive-engine-operator
    alias: mdai-operator
    version: 0.0.10
    repository: https://decisiveai.github.io/mdai-helm-charts
    condition: mdai-operator.enabled
