apiVersion: v2
type: application
name: mdai-cluster
version: 0.6.1
description: MDAI Cluster helm chart
appVersion: 0.6.1
dependencies:
  - name: opentelemetry-operator
    version: ~0.71.2
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-operator.enabled
  - name: kube-prometheus-stack
    alias: kubeprometheusstack
    version: ~65.3.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeprometheusstack.enabled
  - name: metrics-server
    version: ~3.12.1
    repository: https://kubernetes-sigs.github.io/metrics-server
    condition: metrics-server.enabled
  - name: mdai-operator
    version: 0.1.8
    repository: https://decisiveai.github.io/mdai-helm-charts
    condition: mdai-operator.enabled
  - name: event-handler-webservice
    version: 0.0.6
    repository: https://decisiveai.github.io/mdai-helm-charts
    condition: event-handler-webservice.enabled
  - name: valkey
    version: ~2.2.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
