apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggy-mclogface
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loggy-mclogface
  template:
    metadata:
      labels:
        app: loggy-mclogface
    spec:
      containers:
        - name: loggy-mclogface
          image: busybox
          resources:
            limits:
              memory: "16Mi"
              cpu: "50m"
            requests:
              memory: "8Mi"
              cpu: "25m"
          env:
            - name: LOG_MESSAGE
              value: The algorithm successfully executed, triggering neural pathways and producing a burst of optimized data streams.
            - name: LOG_MIN_INTERVAL
              value: "1"  # minimum interval in seconds
            - name: LOG_MAX_INTERVAL
              value: "5"  # maximum interval in seconds
            - name: LOG_MIN_COUNT
              value: "1"
            - name: LOG_MAX_COUNT
              value: "25"
          command:
            - /bin/sh
            - -c
            - |
              LEVELS="ERROR WARNING INFO"
              while true; do
                COUNT=$(( (RANDOM % (${LOG_MAX_COUNT} - ${LOG_MIN_COUNT} + 1)) + ${LOG_MIN_COUNT} ))
                INTERVAL=$(( (RANDOM % (${LOG_MAX_INTERVAL} - ${LOG_MIN_INTERVAL} + 1)) + ${LOG_MIN_INTERVAL} ))
                for i in $(seq 1 $COUNT); do
                  LOG_LEVEL=$(echo $LEVELS | awk -v idx=$((RANDOM % 3 + 1)) '{print $idx}')
                  echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ") - ${LOG_LEVEL} - ${LOG_MESSAGE}"
                done
                sleep $INTERVAL
              done
