fileConfigs:
  01_sources.conf: |-
    <source>
      @type tail
      @label @FLUENT_FORWARD
      path /var/log/containers/*.log
      pos_file /var/log/fluentd/fluentd-containers.log.pos
      tag kubernetes.*
      <parse>
        @type none
        # expression /^(?<time>[^ ]+T[^ ]+Z?) - (?<log_level>[^ ]+) - (?<message>.*)$/
        # time_format %Y-%m-%dT%H:%M:%S%z
      </parse>
    </source>

    # Expose metrics in Prometheus format
    <source>
      @type prometheus
      bind 0.0.0.0
      port 24231
      metrics_path /metrics
    </source>

    <label @FLUENT_FORWARD>
      <filter kubernetes.**>
        @type grep
        <include>
          key kubernetes.pod_name
          pattern loggy-mclogface
        </include>
      </filter>

      <filter kubernetes.**>
        @type record_transformer
        <record>
          service.name ${record["kubernetes"]["pod_name"]}
          severity ${record["log"].scan(/(ERROR|WARNING|INFO)/).first || "INFO"}
          severity_number ${record["log"].scan(/ERROR|WARNING|INFO/).first == 'ERROR' ? 9 : ${record["log"].scan(/WARNING/).first ? 5 : 1}}
        </record>
      </filter>

      <match kubernetes.**>
        @type forward
        <server>
          host gateway-collector.mdai.svc.cluster.local
          port 8006
        </server>
      </match>
    </label>



  02_filters.conf: ""

  03_dispatch.conf: ""

  04_outputs.conf: ""

fluentd:
  resources:
    limits:
      memory: 200Mi
      cpu: 100m
    requests:
      memory: 100Mi
      cpu: 50m

  # Mount the necessary directories to access pod logs
  extraVolumeMounts:
    - name: varlog
      mountPath: /var/log
  extraVolumes:
    - name: varlog
      hostPath:
        path: /var/log
