kube-prometheus-stack:
  enable: true  
  defaultRules:
    create: false
  prometheus-windows-exporter:
    prometheus:
      monitor:
        enabled: false
  alertmanager:
    config:
      route:
        group_by: ["alertname", "service_name"]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'event-handler' 
        routes:
        - matchers:
          - alertname = "Watchdog"
          receiver: 'null'
      receivers:
      - name: 'null'   
      - name: 'event-handler'
        webhook_configs:
          - url: 'http://mdai-api.mdai.svc.cluster.local:8081/alerts'  
            send_resolved: true
    serviceMonitor:
      selfMonitor: false
  grafana:
    enabled: false
    serviceMonitor: 
      enabled: false
  kubernetesServiceMonitors:
    enabled: false
  kubeApiServer:
    enabled: false
  kubelet:
    enabled: false
  kubeControllerManager:
    enabled: false
    serviceMonitor:
      enabled: false
  coreDns:
    enabled: false
    serviceMonitor:
      enabled: false
  kubeEtcd:
    enabled: false
    serviceMonitor:
      enabled: false
  kubeScheduler:
    enabled: false
    serviceMonitor:
      enabled: false
  kubeProxy:
    enabled: false
    serviceMonitor:
      enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  prometheus-node-exporter:
    prometheus:
      monitor:
        enabled: false
  prometheusOperator:
    kubeletService:
      enabled: false
    serviceMonitor:
      selfMonitor: false
  prometheus: 
    serviceMonitor:
      selfMonitor: false
    prometheusSpec:
      additionalArgs:
      - name: enable-feature
        value: exemplar-storage
      - name: enable-feature
        value: otlp-write-receiver
      - name: enable-feature
        value: promql-experimental-functions
      image:
        registry: quay.io
        repository: prometheus/prometheus
        tag: v2.54.1
        sha: ""
      additionalScrapeConfigs:
      - job_name: otel-collector
        honor_labels: true
        tls_config:
          insecure_skip_verify: true
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component, __meta_kubernetes_pod_annotation_prometheus_io_scrape]
            separator: ;
            regex: opentelemetry-collector;true
            action: keep
          - source_labels: [__address__]
            regex: '.*:(431[78]|14250)'
            action: drop
      - job_name: datalyzer-scrape
        honor_labels: true
        tls_config:
          insecure_skip_verify: true
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component, __meta_kubernetes_pod_annotation_prometheus_io_scrape]
            separator: ;
            regex: datalyzer;true
            action: keep
          - source_labels: [__address__]
            regex: '.*:(431[78]|14250)'
            action: drop