replicas: 1
mode: standalone
persistence:
  enabled: true
  size: 10Gi
  storageClass: standard 
resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m
tls:
  enabled: false
buckets:
  - name: "logs"
    policy: "none"
    purge: true 
    lifecycleConfigurations:
      - expiration:
          days: 1
users:
  - accessKey: console
    secretKey: console123
    policy: consoleAdmin
  - accessKey: writer
    secretKey: writer123
    policy: writeonly

svcaccts:
  - accessKey: writer-svcacct
    secretKey: writer123
    user: writer