apiVersion: v1
kind: Secret
metadata:
  name: nats-secret
  labels:
    app: nats
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  NATS_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}