apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  labels:
    app: rabbitmq
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  RABBITMQ_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
  RABBITMQ_ENDPOINT: {{ printf "%s-rabbitmq.%s.svc.cluster.local:%d" .Release.Name .Release.Namespace (int .Values.rabbitmq.service.ports.amqp) | b64enc | quote }}