{{- if not (hasKey .Values "valkey.credentials.password") }}
apiVersion: v1
kind: Secret
metadata:
  name: mdai-valkey-credentials
  labels:
    app: valkey
type: Opaque
data:
  valkey-password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
