{{- if not (hasKey .Values "valkey.credentials.password") }}
apiVersion: v1
kind: Secret
metadata:
  name: valkey-secret
  labels:
    app: valkey
type: Opaque
data:
  VALKEY_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
